channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow<3,>=2.3
  - cloudpickle==2.0.0
  - numpy==1.22.4
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - scipy==1.7.3
name: mlflow-env
